KAFKA_BROKER=${KAFKA_BROKER:="localhost:9092"}
ZOOKEEPER_NODE=${ZOOKEEPER_NODE:="localhost:2181"}
INPUT_TOPIC=${INPUT_TOPIC:=TEST_events}
OUTPUT_EVENT_SUM_TOPIC=${OUTPUT_EVENT_SUM_TOPIC:=TEST_eventSum}
OUTPUT_EVENT_SUM_ACCUMULATED_TOPIC=${OUTPUT_EVENT_SUM_ACCUMULATED_TOPIC:=TEST_eventSumAccumulated}
OUTPUT_ACCUMULATED_IMAGES=${OUTPUT_ACCUMULATED_IMAGES:=True}

java -jar EventMessageVisualisationStreamer.jar -b ${KAFKA_BROKER} -z ${ZOOKEEPER_NODE} -src ${INPUT_TOPIC} -pt ${OUTPUT_EVENT_SUM_TOPIC} -at ${OUTPUT_EVENT_SUM_ACCUMULATED_TOPIC} -ppi ${OUTPUT_ACCUMULATED_IMAGES}
